### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/repro-catalogue#1]
Hey! @KirstieJane asked me to have a look at this repo and share some of my thoughts. Specifically she asked me:

1. what I think
2. can make I sense of the idea / concept
3. does it run
4. what is needed to make it run

---

1. I think the idea of having a tool to version your code and data, and _check that you’re still using the version of code and data you think you’re using_, is a very useful thing. What I’m unclear on is what this gives you extra than, say, git? (e.g. you could compare 2 commits and see the diff). Though this is probably more useful in cases when the data is not in git. But I still feel like it’s an extra responsibility I have to bear.

2. Even though I’ve done a bit of work with hashes, I did find the readme quite confusing. This is probably because it’s more a stream-of-conciousness/scoping document than “proper” polished documentation at the minute. What if the user doesn’t know what a hash is? Is the tool just comparing hashes? What if I find out something’s changed that I didn’t want to? Can I recover it, especially if the data isn’t under git?

There’s talk at some point of data providers maintaining a “version to hash” index. How will we convince them that that’s the right thing to do/convention to adopt? Also that feels like a lot of onus on “other people” to be doing things in a way that are compatible with this tool, maybe the tool should be more flexible to different working patterns?

3. No I haven’t managed to run it :grimacing: In fact, there’s a pretty big syntax error

```bash
$ catalogue engage --input-data foo --code bar 
Traceback (most recent call last):
  File "/Users/sgibson/anaconda3/bin/catalogue", line 11, in <module>
    load_entry_point('catalogue==0.0.0', 'console_scripts', 'catalogue')()
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/catalogue-0.0.0-py3.7.egg/catalogue/parser.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/Users/sgibson/anaconda3/lib/python3.7/site-packages/catalogue-0.0.0-py3.7.egg/catalogue/engage.py", line 11
SyntaxError: 'break' outside loop
```

4. I’m not sure yet. I have [a fork](https://github.com/sgibson91/repro-catalogue/tree/install-instructions) where I was trying to use a setup.py file for installation, but keep running into the aforementioned syntax error. Also there are still some empty functions hanging around so maybe it’s a bit premature to be trying to install and run it.

Hope that’s useful!

**Comment by radka-j** [comment]
All updates from @sgibson91 fork now on the [fix/install](https://github.com/alan-turing-institute/repro-catalogue/tree/fix/install) branch.

**Comment by Islast** [comment]
Sorry @sgibson91 ! the code of course does not run. Everything I wrote was more an outline than anything else (I have a full time job and various other commitments outside of this) and should be thrown own completely if it is not helpful

**Comment by sgibson91** [comment]
No worries @Islast, I think this has given @radka-j and the team useful starting point to work from. Good luck with everything! 💖

**Comment by edaub** [comment]
Thanks for clarifying, @Islast. We greatly appreciate having this as a starting point and the issues are there just to clarify that we weren't missing something (and of course to help us action things we would need to implement).

@radka-j and I are now admins on the repository, so I presume that is a signal that we are free to modify as needed to move DECOVID forward? If not, we are happy to work in a fork if you would rather merge things you are happy with into the main repo on your own schedule!

**Comment by Islast** [comment]
@radka-j  and @edaub I'm totally happy for you to takeover from here onward. Please use the main repo and make whatever changes suit you. Even if that's throwing everything out and starting again in a different language etc. 
If you are going to work with what's already here feel free to @ me whenever you want

**Comment by radka-j** [comment]
Thank you @Islast for all the clarifications and the help! As already mentioned, we really appreciate all that you have done and are just trying to understand what there is left to do. Hope you're well!  :)
